In [ ]:
import numpy as np
import pandas as pd
pd.read_csv("/content/patients (1).csv")

,mean,max,min,STD (signal),STD (R-R),RMSSD,max R-R,min R-R,IQR of R-R,BPM,avg. QRS complex,avg. ST segment,avg. PR interval,label
0,-0.000581,0.478275,-0.082518,0.077975,73.132843,96.871704,1136.666667,926.666667,95.833333,58.056091,29.666667,36.000000,48.555556,0.0
1,-0.000028,0.470885,-0.103189,0.078327,17.984905,20.514223,1013.333333,960.000000,20.000000,60.644805,18.200000,49.200000,NaN,0.0
2,0.000352,0.461577,-0.058427,0.077625,49.566018,57.324612,940.000000,803.333333,83.333333,68.329073,32.300000,34.300000,35.300000,0.0
3,0.000759,0.494339,-0.070465,0.086440,19.204873,27.462095,983.333333,923.333333,20.000000,62.786786,29.300000,31.100000,41.100000,0.0
4,0.000063,0.422451,-0.085829,0.076874,52.821619,56.371782,1000.000000,830.000000,77.500000,66.116180,19.454545,39.090909,43.090909,0.0
5,0.001742,0.482454,-0.155515,0.088208,47.826203,69.801305,990.000000,840.000000,66.666667,64.441848,20.300000,35.500000,51.800000,0.0
6,0.000015,0.361976,-0.246973,0.104554,40.997659,38.369548,913.333333,763.333333,36.666667,71.161339,25.666667,33.083333,NaN,0.0
7,-0.000754,0.330339,-0.074564,0.053127,53.722538,62.282956,1013.333333,863.333333,86.666667,64.225521,29.400000,27.300000,41.500000,0.0
8,0.002059,0.359674,-0.205099,0.068127,42.304640,61.977979,1133.333333,1013.333333,55.833333,55.404427,19.444444,47.222222,52.222222,0.0
9,0.001016,0.408846,-0.117857,0.076563,49.891858,46.188022,993.333333,843.333333,83.333333,65.475858,20.000000,36.900000,34.800000,0.0
10,-0.000787,0.504083,-0.100552,0.090555,19.360135,19.468239,896.666667,836.666667,28.333333,68.521013,19.454545,33.454545,40.090909,0.0
11,0.000259,0.324033,-0.094872,0.059648,47.966739,53.302074,880.000000,693.333333,50.000000,74.782455,16.083333,39.416667,38.083333,0.0
12,-0.007422,0.567948,-0.450304,0.112020,37.694352,42.586151,930.000000,820.000000,58.333333,68.780947,20.727273,35.727273,36.909091,0.0
13,0.000286,0.620542,-0.080425,0.105194,34.924964,55.465204,963.333333,870.000000,60.000000,65.636954,29.900000,22.400000,43.900000,0.0
14,0.000547,0.426756,-0.141107,0.074521,31.773698,37.472212,1046.666667,956.666667,53.333333,60.070304,21.900000,NaN,NaN,0.0
15,0.000709,0.489624,-0.077386,0.092889,18.687064,17.994708,1170.000000,1116.666667,22.500000,52.565659,33.666667,NaN,NaN,1.0
16,0.000102,0.522578,-0.101710,0.088597,32.877840,48.591266,1196.666667,1100.000000,41.666667,52.268941,21.750000,42.625000,56.625000,1.0
17,-0.002600,0.518303,-0.152943,0.093258,18.808770,26.246693,1126.666667,1076.666667,33.333333,54.208683,22.444444,45.555556,48.333333,1.0
18,-0.004538,0.250637,-0.652787,0.078945,31.972210,50.018515,1226.666667,1140.000000,46.666667,50.443180,44.500000,NaN,NaN,1.0
19,0.001233,0.408052,-0.084339,0.064290,32.191762,38.276355,1170.000000,1073.333333,34.166667,53.466461,17.000000,NaN,NaN,1.0
20,-0.001781,0.428158,-0.125117,0.079967,12.963624,16.134357,1110.000000,1073.333333,16.666667,55.157347,37.333333,27.444444,41.000000,1.0
21,-0.000411,0.465140,-0.109807,0.068915,225.319389,268.250505,1120.000000,476.666667,93.333333,57.316215,44.500000,12.200000,43.100000,1.0
22,-0.000109,0.517762,-0.089550,0.084639,13.471506,11.941214,1286.666667,1250.000000,16.666667,47.372441,31.750000,37.125000,54.625000,1.0
23,0.001023,0.553557,-0.306905,0.123458,19.860625,24.358435,1236.666667,1186.666667,21.666667,49.122649,19.714286,34.714286,45.857143,1.0
24,-0.001827,0.682257,-0.291900,0.124801,30.654242,47.659507,1176.666667,1086.666667,40.000000,53.597495,38.666667,39.666667,64.666667,1.0
25,0.002059,0.487871,-0.092266,0.091034,32.829526,48.857313,1233.333333,1143.333333,41.666667,50.024448,20.000000,41.625000,49.875000,1.0
26,0.000408,0.440145,-0.078346,0.068020,16.565167,26.367368,1200.000000,1153.333333,18.333333,50.873289,32.444444,NaN,NaN,1.0